name: my_wallpaper
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  intl: ^0.20.1
  particles_flutter: ^0.1.1
  confetti: ^0.7.0
  carousel_slider: ^5.0.0
  jam_icons: ^0.0.1
  flutter_floating_bottom_bar: ^1.2.0
  dot_navigation_bar: ^1.0.2
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  async_wallpaper: ^2.1.0
  firebase_storage: ^12.4.0
  firebase_database: ^11.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo.png
   - assets/animals.jpg
   - assets/car.jpg
   - assets/nature.jpg
   - assets/space.jpg
   - assets/abstract.jpg
   - assets/wallpaper1.jpg
   - assets/wallpaper2.jpg
   - assets/sky.jpg
   - assets/wallpaper3.jpg
   - assets/wallpaper4.jpg
   - assets/wallpaper5.jpg
   - assets/wallpaper6.jpg
   - assets/profile.png
   - assets/assets/community.jpg
   - assets/assets/popular.jpg
   - assets/assets/curated.jpg
   - assets/assets/trending.jpg
   - assets/assets/car.jpg
   - assets/assets/animal.jpeg
   - assets/assets/anime.jpeg
   - assets/assets/nature.jpeg
   - assets/assets/technology.jpeg
   - assets/assets/space.jpeg
   - assets/assets/pattern.jpg
   - assets/assets/artwok.jpeg
   - assets/assets/sciencefiction.jpeg
   - assets/assets/marvel.jpg
   - assets/assets/god.jpg
   - assets/assets/communityw1.jpg
   - assets/assets/communityw2.jpg
   - assets/assets/communityw3.jpg
   - assets/assets/communityw4.jpg
   - assets/assets/communityw5.jpg
   - assets/assets/curatedw3.jpeg
   - assets/assets/curatedw4.jpg
   - assets/assets/curatedw5.jpeg
   - assets/assets/popularw1.jpg
   - assets/assets/popularw2.jpg
   - assets/assets/trendingw1.jpg
   - assets/assets/trendingw2.jpg
   - assets/assets/carw1.jpg
   - assets/assets/carw2.jpg
   - assets/assets/animalw1.jpg
   - assets/assets/naturew1.jpg
   - assets/assets/naturew2.jpg
   - assets/assets/technologyw1.jpg
   - assets/assets/technologyw3.jpg
   - assets/assets/spacew2.jpeg
   - assets/assets/patternw1.jpeg
   - assets/assets/patternw2.jpeg
   - assets/assets/artworkw1.jpg
   - assets/assets/artworkw2.jpg
   - assets/assets/sciencefictionw1.jpeg
   - assets/assets/sciencefictionw2.jpeg
   - assets/assets/marvelw1.jpeg
   - assets/assets/marvelw2.jpeg
   - assets/assets/godw1.jpg
   - assets/assets/godw2.jpeg

   
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
