// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjS9sVJY7tu32gTRE9jFpZSJ0pAezPlL8',
    appId: '1:1015339334290:web:033b5531f85a5841b4444b',
    messagingSenderId: '1015339334290',
    projectId: 'wallpaper-store-3c0f5',
    authDomain: 'wallpaper-store-3c0f5.firebaseapp.com',
    storageBucket: 'wallpaper-store-3c0f5.firebasestorage.app',
    measurementId: 'G-SMGCPXEHGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xVWLnU5mBjE06xF5jK48Oy1CPR6dK-4',
    appId: '1:1015339334290:android:035d2055411fa74fb4444b',
    messagingSenderId: '1015339334290',
    projectId: 'wallpaper-store-3c0f5',
    storageBucket: 'wallpaper-store-3c0f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqISfMi1FFNhiWWC5_g-bP53F2YLfLu8',
    appId: '1:1015339334290:ios:e6ea5b10490095cab4444b',
    messagingSenderId: '1015339334290',
    projectId: 'wallpaper-store-3c0f5',
    storageBucket: 'wallpaper-store-3c0f5.firebasestorage.app',
    iosBundleId: 'com.example.myWallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsqISfMi1FFNhiWWC5_g-bP53F2YLfLu8',
    appId: '1:1015339334290:ios:e6ea5b10490095cab4444b',
    messagingSenderId: '1015339334290',
    projectId: 'wallpaper-store-3c0f5',
    storageBucket: 'wallpaper-store-3c0f5.firebasestorage.app',
    iosBundleId: 'com.example.myWallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjS9sVJY7tu32gTRE9jFpZSJ0pAezPlL8',
    appId: '1:1015339334290:web:9b00cba3e4d5628ab4444b',
    messagingSenderId: '1015339334290',
    projectId: 'wallpaper-store-3c0f5',
    authDomain: 'wallpaper-store-3c0f5.firebaseapp.com',
    storageBucket: 'wallpaper-store-3c0f5.firebasestorage.app',
    measurementId: 'G-D0TD1FKHT2',
  );
}
